services:
  - type: web
    name: pos-backend
    env: node
    buildCommand: pnpm install && pnpm run db:migrate && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromSecret: true
      - key: VITE_SUPABASE_ANON_KEY
        fromSecret: true